version: "3.9"

services:
  api: 
    container_name: express_api_entrega
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB=products_management
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    container_name: db
    image: postgres:14.3-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=jhon
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jhon -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s